// @generated
// This file is @generated by prost-build.
/// Block header data from BlockStart event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockStart {
    #[prost(uint64, tag="1")]
    pub seqno: u64,
    #[prost(bytes="vec", tag="2")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub uncle_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub coinbase: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub transactions_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="6")]
    pub difficulty: u64,
    #[prost(uint64, tag="7")]
    pub number: u64,
    #[prost(uint64, tag="8")]
    pub gas_limit: u64,
    #[prost(uint64, tag="9")]
    pub timestamp: u64,
    #[prost(bytes="vec", tag="10")]
    pub extra_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub mix_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub nonce: u64,
    #[prost(uint64, repeated, tag="13")]
    pub base_fee_per_gas_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(bytes="vec", tag="14")]
    pub withdrawals_root: ::prost::alloc::vec::Vec<u8>,
}
/// Block execution results from BlockEnd event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockEnd {
    #[prost(uint64, tag="1")]
    pub seqno: u64,
    #[prost(bytes="vec", tag="2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub receipts_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub logs_bloom: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="6")]
    pub gas_used: u64,
}
/// EIP-2930 access list entry
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccessListEntry {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub storage_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxHeader {
    #[prost(uint32, tag="1")]
    pub txn_index: u32,
    #[prost(bytes="vec", tag="2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="5")]
    pub is_contract_creation: bool,
    #[prost(uint64, tag="6")]
    pub nonce: u64,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, repeated, tag="8")]
    pub value_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag="9")]
    pub max_fee_per_gas_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag="10")]
    pub max_priority_fee_per_gas_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag="11")]
    pub r_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag="12")]
    pub s_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(bool, tag="13")]
    pub y_parity: bool,
    #[prost(uint32, tag="14")]
    pub txn_type: u32,
    #[prost(uint64, repeated, tag="15")]
    pub chain_id_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(bytes="vec", tag="16")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag="17")]
    pub access_list: ::prost::alloc::vec::Vec<AccessListEntry>,
}
/// Transaction receipt from TxnEvmOutput event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TxReceipt {
    #[prost(uint32, tag="1")]
    pub txn_index: u32,
    #[prost(bool, tag="2")]
    pub status: bool,
    #[prost(uint64, tag="3")]
    pub gas_used: u64,
    #[prost(uint32, tag="4")]
    pub log_count: u32,
    #[prost(uint32, tag="5")]
    pub call_frame_count: u32,
}
/// Transaction log
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxLog {
    #[prost(uint32, tag="1")]
    pub txn_index: u32,
    #[prost(uint32, tag="2")]
    pub log_index: u32,
    #[prost(bytes="vec", tag="3")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="4")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Call frame (execution trace)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxCallFrame {
    #[prost(uint32, optional, tag="1")]
    pub txn_index: ::core::option::Option<u32>,
    #[prost(uint32, tag="2")]
    pub index: u32,
    #[prost(bytes="vec", tag="3")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub call_target: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub opcode: u32,
    #[prost(uint64, repeated, tag="6")]
    pub value_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag="7")]
    pub gas: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    #[prost(int32, tag="9")]
    pub evmc_status: i32,
    #[prost(uint64, tag="10")]
    pub depth: u64,
    #[prost(bytes="vec", tag="11")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub return_data: ::prost::alloc::vec::Vec<u8>,
}
/// Account access list header
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AccountAccessListHeader {
    #[prost(uint32, optional, tag="1")]
    pub txn_index: ::core::option::Option<u32>,
    #[prost(uint32, tag="2")]
    pub entry_count: u32,
    #[prost(uint32, tag="3")]
    pub access_context: u32,
}
/// Account access (balance/nonce/code changes)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountAccess {
    #[prost(uint32, optional, tag="1")]
    pub txn_index: ::core::option::Option<u32>,
    #[prost(uint32, tag="2")]
    pub index: u32,
    #[prost(bytes="vec", tag="3")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="4")]
    pub access_context: u32,
    #[prost(bool, tag="5")]
    pub is_balance_modified: bool,
    #[prost(bool, tag="6")]
    pub is_nonce_modified: bool,
    #[prost(uint64, repeated, tag="7")]
    pub prestate_balance_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag="8")]
    pub prestate_nonce: u64,
    #[prost(bytes="vec", tag="9")]
    pub prestate_code_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag="10")]
    pub modified_balance_limbs: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag="11")]
    pub modified_nonce: u64,
    #[prost(uint32, tag="12")]
    pub storage_key_count: u32,
}
/// Storage slot access
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageAccess {
    #[prost(uint32, optional, tag="1")]
    pub txn_index: ::core::option::Option<u32>,
    #[prost(uint32, tag="2")]
    pub account_index: u32,
    #[prost(bytes="vec", tag="3")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="4")]
    pub access_context: u32,
    #[prost(uint32, tag="5")]
    pub index: u32,
    #[prost(bool, tag="6")]
    pub modified: bool,
    #[prost(bool, tag="7")]
    pub transient: bool,
    #[prost(bytes="vec", tag="8")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub start_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub end_value: ::prost::alloc::vec::Vec<u8>,
}
/// TX_END marker
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TxEnd {
    #[prost(uint32, tag="1")]
    pub txn_index: u32,
}
// @@protoc_insertion_point(module)
